"""empty message

Revision ID: 47365daba408
Revises: 164665d97417
Create Date: 2018-10-20 17:19:34.252514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47365daba408'
down_revision = '164665d97417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('region', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_region'), 'user', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_region'), table_name='user')
    op.drop_column('user', 'region')
    # ### end Alembic commands ###
