"""empty message

Revision ID: 8c8180053eb1
Revises: eb2539ccb0d2
Create Date: 2018-10-25 11:02:18.585767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8180053eb1'
down_revision = 'eb2539ccb0d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result',
    sa.Column('region', sa.String(length=5), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('eggs_inv', sa.Integer(), nullable=True),
    sa.Column('eggs_stores', sa.Integer(), nullable=True),
    sa.Column('eggs_distance', sa.Integer(), nullable=True),
    sa.Column('bread_inv', sa.Integer(), nullable=True),
    sa.Column('bread_stores', sa.Integer(), nullable=True),
    sa.Column('bread_distance', sa.Integer(), nullable=True),
    sa.Column('milk_inv', sa.Integer(), nullable=True),
    sa.Column('milk_stores', sa.Integer(), nullable=True),
    sa.Column('milk_distance', sa.Integer(), nullable=True),
    sa.Column('tp_inv', sa.Integer(), nullable=True),
    sa.Column('tp_stores', sa.Integer(), nullable=True),
    sa.Column('tp_distance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('region')
    )
    op.create_index(op.f('ix_result_timestamp'), 'result', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_result_timestamp'), table_name='result')
    op.drop_table('result')
    # ### end Alembic commands ###
