"""empty message

Revision ID: eced9e4097d4
Revises: 8c8180053eb1
Create Date: 2018-10-25 11:12:01.740530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eced9e4097d4'
down_revision = '8c8180053eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast',
    sa.Column('region', sa.String(length=5), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('eggs_inv', sa.Integer(), nullable=True),
    sa.Column('eggs_stores', sa.Integer(), nullable=True),
    sa.Column('eggs_distance', sa.Integer(), nullable=True),
    sa.Column('bread_inv', sa.Integer(), nullable=True),
    sa.Column('bread_stores', sa.Integer(), nullable=True),
    sa.Column('bread_distance', sa.Integer(), nullable=True),
    sa.Column('milk_inv', sa.Integer(), nullable=True),
    sa.Column('milk_stores', sa.Integer(), nullable=True),
    sa.Column('milk_distance', sa.Integer(), nullable=True),
    sa.Column('tp_inv', sa.Integer(), nullable=True),
    sa.Column('tp_stores', sa.Integer(), nullable=True),
    sa.Column('tp_distance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('region')
    )
    op.create_index(op.f('ix_forecast_timestamp'), 'forecast', ['timestamp'], unique=False)
    op.drop_index('ix_result_timestamp', table_name='result')
    op.drop_table('result')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result',
    sa.Column('region', sa.VARCHAR(length=5), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('eggs_inv', sa.INTEGER(), nullable=True),
    sa.Column('eggs_stores', sa.INTEGER(), nullable=True),
    sa.Column('eggs_distance', sa.INTEGER(), nullable=True),
    sa.Column('bread_inv', sa.INTEGER(), nullable=True),
    sa.Column('bread_stores', sa.INTEGER(), nullable=True),
    sa.Column('bread_distance', sa.INTEGER(), nullable=True),
    sa.Column('milk_inv', sa.INTEGER(), nullable=True),
    sa.Column('milk_stores', sa.INTEGER(), nullable=True),
    sa.Column('milk_distance', sa.INTEGER(), nullable=True),
    sa.Column('tp_inv', sa.INTEGER(), nullable=True),
    sa.Column('tp_stores', sa.INTEGER(), nullable=True),
    sa.Column('tp_distance', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('region')
    )
    op.create_index('ix_result_timestamp', 'result', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_forecast_timestamp'), table_name='forecast')
    op.drop_table('forecast')
    # ### end Alembic commands ###
